### ISSUE TITLE
路径错误

### ISSUE THREAD

**Issue by lavyun** [F-loat/mpvue-quickstart#1]
VM45:1 thirdScriptError 
 sdk uncaught third Error 
 module "static/js/manifest.js" is not defined 
 Error: module "static/js/manifest.js" is not defined
    at require (http://127.0.0.1:60060/appservice/__dev__/WAService.js:18:27142)
    at http://127.0.0.1:60060/appservice/__dev__/WAService.js:18:26997
    at http://127.0.0.1:60060/appservice/pages/index.js:3:1
    at require (http://127.0.0.1:60060/appservice/__dev__/WAService.js:18:27248)
    at http://127.0.0.1:60060/appservice/appservice:1204:9

**Comment by F-loat** [comment]
我这边没问题，你初始化时的选项都选了什么

**Comment by lavyun** [comment]
use vuex? y
use eslint? n
其他的一路回车

**Comment by F-loat** [comment]
你什么时候创建的项目？重新创建下试试
