### ISSUE TITLE
初始化项目之后，为什么没有page.js

### ISSUE THREAD

**Issue by dxwb** [F-loat/mpvue-quickstart#17]
我照着npm上的文档做，但是quickstart的项目没有page.js，是新版本有替代方案了吗，有点懵

**Comment by F-loat** [comment]
新版 mpvue-entry 默认读取 app.json 里的配置，可以看下 mpvue-entry 的文档

**Comment by dxwb** [comment]
文档看过了，但是文档最下方又看到一个tips是关于page.json的，所以就懵了

**Comment by F-loat** [comment]
那块修改时漏掉了，已经更正
