### ISSUE TITLE
热更新后报错

### ISSUE THREAD

**Issue by BarryZhan** [F-loat/mpvue-quickstart#19]
第一次编译项目可以正常运行，修改文件热更新后就报错
![image](https://user-images.githubusercontent.com/11763811/50019694-958b7e80-000e-11e9-9540-2d3a029da0da.png)

**Comment by F-loat** [comment]
我这边没遇到，提供下完整的复现步骤？或者你重新初始化安装依赖试试

**Comment by BarryZhan** [comment]
我之前是用的官方模板生成的，然后把想迁移到这个模板。就用您这个模板初始化了一个，把 src 和 static 拷进了新初始化的这个里面。运行第一次是正常的，修改任意文件热更新后就会报错，我把node_modules删除重新安装也还是这个现象。
我把代码上传上了github上面，[仓库地址](https://github.com/BarryZhan/mpvue-test) 您有空的时候能帮我看看吗？

**Comment by F-loat** [comment]
你这个也没问题的啊，是改哪个文件会出错

**Comment by F-loat** [comment]
有问题再重开 issue
