### ISSUE TITLE
在pages中使用文件夹形式新增页面，编译生成文件中缺少template文件

### ISSUE THREAD

**Issue by feng-fu** [F-loat/mpvue-quickstart#2]
使用quickstart新建项目，在pages中以文件夹的方式新增一个test文件夹，在其中分别新建main.js 和 index.vue文件
```
// main.js
import App from './index'
import Vue from 'vue'
import store from '@/store'

const app = new Vue({
  store,
  ...App
})
app.$mount()
export default {
  config: {
  }
}
// index.vue

<template>
  <div>this is a test. {{message}}</div>
</template>
<script>
export default {
  data () {
    return {
      message: '12312312'
    }
  }
}
</script>
```
在`pages.js`文件中配置该路径
![image](https://user-images.githubusercontent.com/20320122/42794693-d8191b22-89b2-11e8-9849-acdc349fc21a.png)

进行打包后缺少`pages/test/main/template`文件夹，该文件夹内文件被`pages/test/main.wxml`引用

![image](https://user-images.githubusercontent.com/20320122/42794733-0ab44ffc-89b3-11e8-87a0-e63a6fe2e727.png)

**Comment by F-loat** [comment]
这个模板是搭配 mpvue-entry 使用的，你想用普通的那种方式需要自己修改下 webpack 的入口配置

**Comment by feng-fu** [comment]
嗯，所以mpvue-entry不支持这种方式吗

**Comment by F-loat** [comment]
你看下 mpvue-entry 的文档，页面不需要 main.js 文件的

**Comment by F-loat** [comment]
pages.js 里配置的是 vue 文件的路径

**Comment by feng-fu** [comment]
谢谢
