### ISSUE TITLE
初始化项目后出现各种报错

### ISSUE THREAD

**Issue by zhangzilong1992** [F-loat/mpvue-quickstart#20]
平台：windows 10 x64
npm install后 npm run dev出现eslint包未装，但是在前面并未添加eslint
安装相关npm包后npm run dev出现
![image](https://user-images.githubusercontent.com/33406752/50216303-58354100-03c0-11e9-9553-660f9ce9007d.png)

**Comment by F-loat** [comment]
eslint 的问题已经修正了，你有自己修改什么配置吗

**Comment by viryHd** [comment]
我跟你的情况一模一样，我也是windows

**Comment by F-loat** [comment]
我也是 windows 但我没问题的啊，你们提供下每一步的选项和 node 版本、npm 源之类的信息？

**Comment by viryHd** [comment]
node v10.13.0 (开始是8.12的，我还特地升了级)
npm 6.4.1
初始化没选eslint, 其他默认；
vsCode;
别的没了。
你的也是有这三个文件？@别名，我试试把它改成相对路径看看

**Comment by F-loat** [comment]
你重新初始化试下？

**Comment by viryHd** [comment]
![snipaste_2018-12-19_20-35-50](https://user-images.githubusercontent.com/42270969/50221476-33e16080-03d0-11e9-9f81-1f818d71e0c5.png)
重来也是这样。这三个文件这样。然后@这里报错。你也是这样的三个文件，然后不报错？

**Comment by F-loat** [comment]
是的，mpvue-entry 目前就是这样实现的

**Comment by F-loat** [comment]
我试了下，之前 eslint 配置有问题，只安装缺少的依赖就会导致这个问题，需要手动去掉相关配置，或者重新初始化即可

https://github.com/F-loat/mpvue-quickstart/blob/master/template/build/webpack.base.conf.js#L38-L46

**Comment by zhangzilong1992** [comment]
解决了，多谢

**Comment by keycz** [comment]
@zhangzilong1992 我也是这个问题 请问你是怎么解决的？
