### ISSUE TITLE
内置的vantapp全局组件使用不了

### ISSUE THREAD

**Issue by geekape** [F-loat/mpvue-quickstart#21]
使用的这个脚手架构建的项目，把以前src下的源码复制到这个项目下，在全局`app.vue`中写全局插件，无法自动生成`.json`的插件配置
![image](https://user-images.githubusercontent.com/27131698/50216937-2fae4680-03c2-11e9-896f-7b8b5ae0781b.png)
![image](https://user-images.githubusercontent.com/27131698/50216957-3dfc6280-03c2-11e9-9b7b-02fbf9f226a6.png)

**Comment by F-loat** [comment]
看下安装的 mpvue-config-loader 是哪个版本，重新 run dev 后会生成吗

**Comment by geekape** [comment]
现在只有头一个文件夹的页面可以生成全局插件配置，`mpvue-config-loader`是"^0.1.0"
![image](https://user-images.githubusercontent.com/27131698/50258284-edc0e700-0439-11e9-9d8c-e974a2c3adec.png)

**Comment by geekape** [comment]
每个页面添加 `mpType: 'page'`就可以了，
![image](https://user-images.githubusercontent.com/27131698/50258955-0aaae980-043d-11e9-8d34-e3e70e726b98.png)

![image](https://user-images.githubusercontent.com/27131698/50258983-23b39a80-043d-11e9-92b5-cd1ca17f6bc0.png)

**Comment by F-loat** [comment]
嗯，也可以把 config 这部分移动到 vue 文件里，这样 app.json 里的 pages 是一个字符串的数组就行

**Comment by F-loat** [comment]
另外现在微信小程序官方已经支持全局组件了，可以直接在 app.json 里配置

**Comment by geekape** [comment]
好的，Thanks，还有一个问题就是`app.json`里面的路由可以分模块吗？就像vue-router里的路由一样
![image](https://user-images.githubusercontent.com/27131698/50261964-db4ea980-0449-11e9-89af-4b6d666d5a0e.png)

**Comment by F-loat** [comment]
可以的，默认是 app.json，自定义为 config.js 就行，这个文件是直接 require 处理的
