### ISSUE TITLE
分包怎么配置

### ISSUE THREAD

**Issue by zybieku** [F-loat/mpvue-quickstart#23]
![image](https://user-images.githubusercontent.com/15903330/50411064-01a08a80-0838-11e9-98aa-690ad4cb48bb.png)
老大,我想使用官方的分包配置,应该怎么配置

**Comment by F-loat** [comment]
app.json 里直接配置就行，最新版的 mpvue-entry 有做兼容

**Comment by zybieku** [comment]
但是我上面那样的配置报错
![image](https://user-images.githubusercontent.com/15903330/50411168-ec782b80-0838-11e9-9a23-ba3d274d59d3.png)
大佬的起手式,其他的都没改,就改了app.json,还有vant我只想导入几个UI组件,怎么配置

**Comment by zybieku** [comment]
@F-loat 老大,可以分包,我手动把mpvue-entry 依赖了最新版

**Comment by F-loat** [comment]
👌有问题可以再反馈

**Comment by F-loat** [comment]
vant 按需引入可以自己配置，社区有相关实现

**Comment by zybieku** [comment]
ok,我去看看,大佬开赞赏嘛

**Comment by F-loat** [comment]
😂我回头考虑看看

**Comment by zybieku** [comment]
![image](https://user-images.githubusercontent.com/15903330/50579655-0ab9d900-0e82-11e9-8acf-db2e51dba506.png)
老大,建议把你的起手式文档,改一下,区分下这是插件之后的地址,很多人看你的起手式名字,以为就是官方的那个,然后就没有使用这个了
