### ISSUE TITLE
怎么替换vant的基础样式？

### ISSUE THREAD

**Issue by zhangkaic** [F-loat/mpvue-quickstart#24]

**Comment by F-loat** [comment]
什么意思？样式可以直接覆盖吧

**Comment by zhangkaic** [comment]
有赞是个基础样式的，比如button-primary-color,我是想把这种基础样式替换掉，但是这里面好像是直接引用了有赞的dist，里面组件的样式都是编译完成的wxss，这个问题应该是解决不了的

**Comment by F-loat** [comment]
那你改成自定义的 vant 不就行了
