### ISSUE TITLE
分包情况下无法使用小程序官方插件，比如腾讯插件

### ISSUE THREAD

**Issue by godpan** [F-loat/mpvue-quickstart#25]
分包情况下无法使用小程序官方插件，比如腾讯插件，具体如下：
app.json
`
![2019-01-09 16 36 15](https://user-images.githubusercontent.com/17349682/50886986-e5523f80-142c-11e9-9bfd-e9da4d4f9cdf.png)

`
detail.vue:

`
![2019-01-09 16 36 48](https://user-images.githubusercontent.com/17349682/50886999-ee431100-142c-11e9-9ee8-bdc3a6e03e2e.png)

`
报错提示：

![2019-01-09 16 37 12](https://user-images.githubusercontent.com/17349682/50887016-fb600000-142c-11e9-9922-e5a8a5523e1b.png)

**Comment by F-loat** [comment]
插件目前只能全局配置，后面会优化这块

**Comment by godpan** [comment]
貌似全局配置也无效
![2019-01-09 16 47 41](https://user-images.githubusercontent.com/17349682/50887531-5f36f880-142e-11e9-9b71-bfd0b47181ed.png)

是指在分包里页面不能使用插件吗？

**Comment by F-loat** [comment]
分包里可以用吧，只是不能配置在分包里，可以看下生成的 app.json 有没有问题

**Comment by godpan** [comment]
![2019-01-09 16 52 46](https://user-images.githubusercontent.com/17349682/50887788-0b78df00-142f-11e9-8faa-a511c12a0332.png)
生成的没有问题，之前使用老的main.js的方式是行的，用新的这个架构方式好像有问题。

**Comment by F-loat** [comment]
你清下缓存然后重启下开发工具看看，app.json 没问题应该就可以的

**Comment by godpan** [comment]
问题出在
![2019-01-09 16 36 48](https://user-images.githubusercontent.com/17349682/50897677-cca35300-1447-11e9-9714-e981729ae52b.png)

这种方式编译后的json文件会有问题：

<img width="387" alt="2019-01-09 19 51 24" src="https://user-images.githubusercontent.com/17349682/50897734-fc525b00-1447-11e9-9160-c5aea496748f.png">

多了一个**/**，去掉就好了
