### ISSUE TITLE
webpack中配置问题

### ISSUE THREAD

**Issue by weiyunpeng** [F-loat/mpvue-quickstart#3]
webpack这样配置的话也会将app,manifest,vendor都分别生成文件夹。而app.js中的引用路径还是./static/js/manifest，./static/js/vendor， 和./static/js/app 这样的话路径其实是有问题的呀

**Comment by F-loat** [comment]
具体是会有什么问题，我之前有测过这个应该

**Comment by weiyunpeng** [comment]
你可以清空dist文件再试试

**Comment by F-loat** [comment]
同步官方模板了，你可以试试

**Comment by F-loat** [comment]
你当时用的模板应该就有点旧，中间有修复过一些问题

**Comment by weiyunpeng** [comment]
恩，还用这样子是没问题的。
