### ISSUE TITLE
请问大大会出兼容mpvue2.0的版本吗?

### ISSUE THREAD

**Issue by coolRoger** [F-loat/mpvue-quickstart#30]
Mpvue 2.0 的版本已经出了, 可是使用了这个起手式生成的package.json, 发现mpvue的版本还是1.0.0,
请问会后续出针对mpvue2.0的版本吗?

**Comment by F-loat** [comment]
多平台支持这个模板不打算跟进，entry 和 config 相关的优化会考虑给官方提 pr

**Comment by tianlinzx** [comment]
不跟进多平台没关系，能不能把依赖升级到2.0相关的？

**Comment by F-loat** [comment]
相关依赖已更新
