### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by 7saint** [F-loat/mpvue-quickstart#36]
![1](https://user-images.githubusercontent.com/22890045/56846949-e473e980-6907-11e9-8f59-260c56be3959.png)

是我缺少什么配置么

**Comment by shrekuu** [comment]
发现此报错会在 node 11 下出现, node 10 下不会出现.
node  11 可能哪里有不兼容更新了. 坐等作者更新兼容 node 11 :D .

**Comment by 7saint** [comment]
> 发现此报错会在 node 11 下出现, node 10 下不会出现.
> node 11 可能哪里有不兼容更新了. 坐等作者更新兼容 node 11 :D .

试了node 10 ,确实是可以运行，谢谢

**Comment by F-loat** [comment]
已修复，更新 mpvue-entry 即可
