### ISSUE TITLE
关于publicPath

### ISSUE THREAD

**Issue by fandudu** [F-loat/mpvue-quickstart#6]
应用：我小程序图片是放在cdn上的，生产环境需要配置统一域名，配置publicPath之后发现没用，发现是重写了
![image](https://user-images.githubusercontent.com/15722726/44318471-ba108900-a468-11e8-93f2-6ece8e6f7778.png)请问我要怎么解决，不改动包的情况下

**Comment by F-loat** [comment]
可以加个 loader 预先 replace 一下？帮你 @linrui1994

**Comment by steinslin** [comment]
是在cdn上的图片  直接使用绝对路径就可以了吧。 publicPath怎么样都会存在，没法知道是想放cdn，还是想放本地
